"""schedsim: simulate kube-scheduler placement decisions.

Usage:
  python -m schedsim up             # build/start the control-plane container
  python -m schedsim run input.yaml [--json] [--keep]
  python -m schedsim gen [options] [-o out.yaml]   # synthesise a scenario
  python -m schedsim down           # remove the container
"""

import argparse
import json
import sys

from . import apiclient, cluster, generate, presentation


def load_config(path):
    with open(path) as f:
        text = f.read()
    try:
        import yaml
        return yaml.safe_load(text)
    except ImportError:
        try:
            return json.loads(text)
        except ValueError:
            raise SystemExit(
                "PyYAML is not installed and the input is not JSON. "
                "Install it with: pip install pyyaml")


def dump_config(config, as_json=False):
    header = f"# generated by schedsim gen: {generate.summarize(config)}\n"
    if not as_json:
        try:
            import yaml
            return header + yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
        except ImportError:
            pass  # JSON is valid input too
    return json.dumps(config, indent=2) + "\n"


def do_run(server, config, timeout, keep):
    """Drive apiclient.run(), rendering progress as it streams in.

    Returns the final rows; exits the process on a server-reported error.
    """
    rows = None
    for event in apiclient.run(server, config, timeout=timeout, keep=keep):
        phase = event["phase"]
        if phase == "done":
            rows = event["rows"]
            break
        if phase == "error":
            raise SystemExit(f"run failed: {event['message']}")
        presentation.print_progress(event)
    if rows is None:
        raise SystemExit("run ended unexpectedly with no result "
                         "(did the server connection drop?)")
    return rows


def main():
    parser = argparse.ArgumentParser(prog="schedsim", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("up", help="start the control-plane container")
    sub.add_parser("down", help="remove the control-plane container")
    run_p = sub.add_parser("run", help="schedule workloads onto nodes and print the allocation")
    run_p.add_argument("input", help="YAML/JSON file with nodes: and workloads:")
    run_p.add_argument("--json", action="store_true", help="machine-readable output")
    run_p.add_argument("--csv", help="write full per-pod results here as CSV; "
                       "prints a summary to stdout instead of the table")
    run_p.add_argument("--keep", action="store_true",
                       help="leave nodes/pods in the cluster for inspection")
    run_p.add_argument("--timeout", type=int, default=30,
                       help="seconds to wait for scheduling decisions")
    gen_p = sub.add_parser("gen", help="generate a synthetic nodes/workloads scenario")
    gen_p.add_argument("-o", "--output", help="write here instead of stdout")
    gen_p.add_argument("--json", action="store_true", help="emit JSON instead of YAML")
    gen_p.add_argument("--seed", type=int, help="seed for reproducible scenarios")
    gen_p.add_argument("--nodes", type=int, default=10, help="number of hosts")
    gen_p.add_argument("--node-cpu", default="8", help="processors per host (e.g. 8, 500m)")
    gen_p.add_argument("--node-memory", help="memory per host; default --memory-per-cpu x cpu")
    gen_p.add_argument("--memory-per-cpu", default="4Gi",
                       help="host memory per processor when --node-memory is unset")
    gen_p.add_argument("--zones", type=int, default=0,
                       help="spread nodes across N zone labels (0 = no zone labels)")
    gen_p.add_argument("--workloads", type=int, default=10, help="number of workloads")
    gen_p.add_argument("--replicas", default="mixture:4,0.05",
                       help="instances per workload: fixed:N | uniform:LO,HI | exp:MEAN | "
                            "pareto:MIN,ALPHA | mixture:BASE,P,MAX (default: 4 pods, "
                            "5%% of workloads scale up to 80%% of the nodes)")
    gen_p.add_argument("--cpu", default="fixed:500m",
                       help="cpu demand per instance, same distribution syntax "
                            "(values accept k8s units, e.g. uniform:100m,2)")
    gen_p.add_argument("--memory-per-pod-cpu", default="2Gi",
                       help="pod memory request per cpu of demand")
    gen_p.add_argument("--name-prefix", default="app", help="workload name prefix")

    args = parser.parse_args()

    if args.command == "up":
        cluster.up()
        print("control plane ready at https://127.0.0.1:6443")
    elif args.command == "down":
        cluster.down()
        print("removed")
    elif args.command == "run":
        config = load_config(args.input)
        server = cluster.up()
        rows = do_run(server, config, timeout=args.timeout, keep=args.keep)
        if args.csv:
            presentation.write_csv(rows, args.csv)
            print(f"wrote {len(rows)} rows to {args.csv}")
            presentation.print_summary(rows)
        elif args.json:
            print(json.dumps(rows, indent=2))
        else:
            presentation.print_summary(rows)
            print("\nfor full per-pod results, rerun with --csv FILE or --json",
                  file=sys.stderr)
        if any(r["node"] is None for r in rows):
            sys.exit(2)
    elif args.command == "gen":
        config = generate.generate(
            nodes=args.nodes, node_cpu=args.node_cpu, node_memory=args.node_memory,
            memory_per_cpu=args.memory_per_cpu, zones=args.zones,
            workloads=args.workloads, replicas=args.replicas, cpu=args.cpu,
            memory_per_pod_cpu=args.memory_per_pod_cpu, seed=args.seed,
            name_prefix=args.name_prefix)
        text = dump_config(config, as_json=args.json)
        if args.output:
            with open(args.output, "w") as f:
                f.write(text)
            print(f"wrote {args.output}: {generate.summarize(config)}", file=sys.stderr)
        else:
            sys.stdout.write(text)


if __name__ == "__main__":
    main()
